%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/patrick/Documents/PMP/Analysts/ETF Project/bb_stock_prices.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 09-Oct-2018 17:13:37

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 26);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:Z117";

% Specify column names and types
opts.VariableNames = ["Dates", "HDUSEquity", "TJXUSEquity", "FISVUSEquity", "CSCOUSEquity", "MAUSEquity", "ISRGUSEquity", "MMMUSEquity", "ACNUSEquity", "PGRUSEquity", "NEEUSEquity", "MOUSEquity", "RTNUSEquity", "MONUSEquity", "INTUUSEquity", "JNJUSEquity", "AFLUSEquity", "SYKUSEquity", "NOCUSEquity", "BLKFDSUSEquity", "VUSEquity", "INTCUSEquity", "TUSEquity", "PFEUSEquity", "BRUSEquity", "WMUSEquity"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, 20, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 20, "EmptyFieldRule", "auto");

% Setup rules for import
opts = setvaropts(opts, [2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26], "FillValue", 0);

% Import the data
Data = readtable("/home/patrick/Documents/PMP/Analysts/ETF Project/bb_stock_prices.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts